### ISSUE TITLE
这样的 require 不会太乱了么

### ISSUE THREAD

**Issue by monkeycraps** [sorrycc/spm-project-example1#2]
require('../modules/mod1');
不同目录想要依赖同一mod 的时候写法都不一样

**Comment by sorrycc** [comment]
为什么要一样? require 本地文件肯定是相对路径吧。

**Comment by monkeycraps** [comment]
可是这样，打包的时候就会打包多份进去啦

**Comment by sorrycc** [comment]
不会打包多份的，build 的时候会分析的。
